name: Build Container Image
on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build Container
      run: ./mvnw spring-boot:build-image
    - name: Tag Container
      run: docker tag docker.io/library/k8s-microservice-demo-frontend:0.0.1-SNAPSHOT brianmmcclain/k8s-microservice-demo-frontend:0.0.1-SNAPSHOT
    - name: Push Container
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: brianmmcclain/k8s-microservice-demo-frontend
        tags: latest