name: Build Container Image
on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Checkout main branch
      run: git checkout main
    - name: Build Container
      run: ./mvnw spring-boot:build-image